[workspace]
resolver = "2"
default-members = ["crates/*"]
members = ["crates/*", "contracts/*"]

[workspace.package]
repository = "https://github.com/ahalabs/scaffold-stellar"

[workspace.dependencies]
stellar-scaffold-macro = { path = "crates/stellar-scaffold-macro" }
stellar-registry = { path = "crates/stellar-registry" }

loam-sdk = { git = "https://github.com/loambuild/loam", rev = "096da30cedd371651906cfbed034b955c7b50ab4" }
loam-subcontract-core = { git = "https://github.com/loambuild/loam", rev = "096da30cedd371651906cfbed034b955c7b50ab4" }
stellar-cli = { git = "https://github.com/AhaLabs/stellar-cli", branch = "feat/expose-build-custom-cmd", package = "soroban-cli" }
soroban-rpc = { package = "stellar-rpc-client", version = "22.0.0" }

soroban-sdk = "22.0.0-rc.3"
stellar-xdr = "22.0.0-rc.1.1"
stellar-strkey = "0.0.11"

cargo_metadata = "0.18.1"
thiserror = "1.0.38"
sha2 = "0.10.8"

[profile.contracts]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true

[workspace.lints.clippy]
