[workspace]
resolver = "2"
default-members = ["crates/*"]
members = ["crates/*", "contracts/*"]

[workspace.package]
repository = "https://github.com/ahalabs/scaffold-stellar"

[workspace.dependencies]
loam-sdk = { git = "https://github.com/loambuild/loam", version = "0.6.16" }
loam-build = { git = "https://github.com/loambuild/loam", version = "0.7.3" }
loam-subcontract-core = { git = "https://github.com/loambuild/loam", version = "0.7.9" }

soroban-sdk = "22.0.0-rc.3"
stellar-xdr = "22.0.0-rc.1.1"
stellar-strkey = "0.0.11"

cargo_metadata = "0.18.1"
thiserror = "1.0.38"
sha2 = "0.10.8"

[profile.contracts]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true


[workspace.lints.clippy]
unexpected_cfgs = "allow"